# -*- coding: utf-8 -*-

from __future__ import absolute_import

WATING_DATABASE_NAME = "waiting"
REGISTRATIONS_TABLE_NAME = "tb_registrations"

class RegStatus:
    UNDEFINED = -1
    REGISTERED = 0
    ENTERED = 1
    CANCELLED = 2
    NOT_ENTERED = 3


class RegsTableHeader:
    REGISTRATION_ID = "REGISTRATION_ID"
    STORE_ID = "STORE_ID"
    WAITING_ORDER = "WAITING_ORDER"
    PHONE_NUMBER = "PHONE_NUMBER"
    TEAM_SIZE = "TEAM_SIZE"
    TIMESTAMP = "TIMESTAMP"
    STATUS = "STATUS"

TOTAL_REGISTRATIONS = "TOTAL_REGISTRATIONS"
TOTAL_WAITING_MINUTES = "TOTAL_WAITING_MINUTES"
WAITING_MINUTES_PER_TEAM = "WAITING_MINUTES_PER_TEAM";

TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M:%S.%f"
